services:
  InspiredMinds\ContaoEventlistExtendedBundle\EventListener\GetAllEventsListener:
    public: true

  InspiredMinds\ContaoEventlistExtendedBundle\EventListener\ParseTemplateListener:
    public: true
