services:
    _defaults:
        autowire: true
        autoconfigure: true

    InspiredMinds\ContaoEventlistExtendedBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoEventlistExtendedBundle.php}
